# Coroutine Scope 함수를 알기 전 방법

먼저 가장 간단한 방법으론 suspend 함수에서 다른 suspend 함수를 호출하는 방법이 있다.

하지만 이 방법에 문제가 있는데, **동시에 두 API를 호출할 수 없다.**

즉, 한 API를 호출하여 결과를 받은 후에 다음 API를 호출한다는 뜻이다.

``` kotlin
suspend fun getUserProfile(): UserProfileData {
    val user = getUserData() // 1초
    val notifications = getNotifications() // 1초
    
    return UserProfileData(
        user = user,
        notifications = notifications,
    )
}
// 총 2초가 걸림
```

가장 간단하게 두 API를 동시에 호출하는 방법은 `async`를 이용하는 방법이다.

하지만, `GlobalScope`를 이용해야 하는데, 이것은 추천되지 않는 방법이다.

``` kotlin
suspend fun getUserProfile(): UserProfileData {
    val user = GlobalScope.async { getUserData() }
    
    val notifications = GlobalScope.async {
        getNotifications()
    }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await()
    )
}
```

`GlobalScope`를 사용하게 되면 부모와의 관계가 없게 되는데, 다음과 같은 문제가 있다.

- 부모가 cancel되어도 cancel되지 않는다.
- 부모로부터 context를 물려받지 않는다.

이에 따라 다음 문제가 생길 수 있다.

- 불필요한 연산으로 인한 메모리 누수
- 단위 테스트에서 정상적으로 동작하지 않기 때문에 테스트가 어려워짐

<br>

또 다른 방법으로, scope를 파라미터로 받아 `async`로 실행시켜 보자.

``` kotlin
suspend fun getUserProfile(scope: CoroutineScope): UserProfileData {
    val user = scope.async { getUserData() }
    val notifications = scope.async { getNotifications() }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await(),
    )
}

// 다음 코드와 같다.
suspend fun CoroutineScope.getUserProfile(): UserProfileData {
    val user = async { getUserData() }
    val notifications = async { getNotifications() }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await(),
    )
}
```

cancel이나 unit test가 제대로 동작하기 때문에 이 방법이 훨씬 낫다.

문제는, 함수에서 함수로 Scope를 파라미터로 넘겨야 하기 때문에 부수 효과가 일어날 수 있다.

예를 들어, 하나의 `async`에서 Exception이 발생하게 되면 모든 Coroutine이 cancel되게 된다.

> SupervisorJob이 아니라는 가정 하에

게다가, Scope에 접근하기 쉬워지기 때문에 악용될 가능성이 있다.

``` kotlin
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)

fun getFollowersNumber(): Int = throw Error("Service exception")
suspend fun getUserName(): String {
    delay(500)
    return "marcinmoskala"
}

suspend fun getTweets(): List<Tweet> {
    return listOf(Tweet("Hello, world"))
}

suspend fun getUserDetails(): Details {
    return coroutineScope {
        val userName = async { getUserName() }
        val followersNumber = async { getFollowersNumber() }
        Details(userName.await(), followersNumber.await())
    }
}

fun main() = runBlocking {
    val details = try {
        getUserDetails()
    } catch (e: Error) {
        null
    }

    val tweets = async { getTweets() }
    println("User: $details")
    println("Tweets: ${tweets.await()}")
}

// 예외만 던져진다.
```

위 코드에서 `getUserDetails()`를 실패하더라도 최소한 Tweets가 출력해주고 싶다.

하지만 `getUserDetails()`에서 예외가 발생하게 되면 전체 scope가 cancel된다.

# coroutineScope

CoroutineScope는 scope를 실행시키는 suspend 함수로, 파라미터로 들어온 함수를 실행시켜 값을 반환해 준다.

``` kotlin
suspend fun <R> coroutineScope(
    block: suspend CoroutineScope.() -> R
): R
```

`async`나 `launch`와 다르게 파라미터로 넘긴 body가 종료될때까지 부모의 suspend가 걸리게 된다.

따라서 동시성 작업을 실행하지 않게 된다.

<br>

다음 예제를 보자.

``` kotlin
fun main() = runBlocking {
    val a = coroutineScope {
        delay(1000)
        10
    }
    
    println("a is calculated")
    
    val b = coroutineScope {
        delay(1000)
        20
    }
    
    println(a) // 10
    println(b) // 20
}

// 1초 뒤
a is calculated
// (1 sec)
10
20
```

coorutineScope는 밖에서(`runBlocking`) scope를 상속받긴 하지만, `Job`을 overriding하게 된다.

다음과 같은 특징을 가지게 된다.

- 부모로부터 context를 상속받는다.
- 자신이 끝날 수 있을 때까지 모든 자식을 suspend한다.
- 부모가 cancel되면 모든 자식을 cancel시킨다.

<br>

위에서 말했던 특징 때문에 다음 코드에서 마지막에 After가 출력되는걸 볼 수 있다.

또한, `CoroutineName`이 적절하게 부모에서 자식으로 넘어가는걸 볼 수 있다.

``` kotlin
suspend fun longTask() = coroutineScope {
    launch {
        delay(1000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 1")
    }
    
    launch {
        delay(2000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 2")
    }
}

fun main() = runBlocking(CoroutineName("Parent")) {
    println("Before")
    longTask()
    println("After")
}

Before
// 1초 뒤
[Parent] Finished task 1
// 1초 뒤
[Parent] Finished task 2
After
```

다음 코드에서는 cancel이 어떻게 동작하는지 볼 수 있다.

``` kotlin
suspend fun longTask() = coroutineScope {
    launch {
        delay(1000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 1")
    }
    
    launch {
        delay(2000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 2")
    }
}


fun main(): Unit = runBlocking {
    val job = launch(CoroutineName("Parent")) {
        longTask()
    }
    delay(1500)
    job.cancel()
}
// [Parent] Finished task 1
```

coroutineBuilder들과 다르게, coroutineScope에게서 예외가 발생했을 때, **다른 자식들을 모두 cancel시키고 예외를 다시 던진다.**

이게 `coroutineScope`로 아까 전 Tweet을 출력하는 예제를 고칠 수 있는 이유이다.

아까 전의 예제는 다음과 같이 수정된다.

> 같은 예외가 던져진다는걸 확인하기 위해 Error를 ApiException이라는 클래스를 만들어서 던져줬다.

``` kotlin
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)

class ApiException(
    val code: Int,
    message: String
) : Throwable(message)

fun getFollowersNumber(): Int =
    throw ApiException(500, "Service unavailable")

suspend fun getUserName(): String {
    delay(500)
    return "marcinmoskala"
}

suspend fun getTweets(): List<Tweet> {
    return listOf(Tweet("Hello, world"))
}

suspend fun getUserDetails(): Details = coroutineScope {
    val userName = async { getUserName() }
    val followersNumber = async { getFollowersNumber() }
    Details(userName.await(), followersNumber.await())
}

fun main() = runBlocking {
    val details = try {
        getUserDetails()
    } catch (e: ApiException) {
        null
    }
    
    val tweets = async { getTweets() }
    println ("User: $details")
    println ("Tweets: ${tweets.await()}")
}

User: null
Tweets: [Tweet(text=Hello, world)]
```

`coroutineScope`는 suspend 함수들을 병렬로 실행하는 최선의 방법중 하나이다.

``` kotlin
suspend fun getUserProfile(): UserProfileData = coroutineScope {
    val user = async { getUserData() }
    val notifications = async { getNotifications() }
    
    UserProfileData(
        user = user.await(),
        notifications = notifications.await(),
    )
}
```

요즘은 다음과 같이 main함수에 `coroutineScope`를 많이 사용하는 추세이다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    launch {
        delay(1000)
        println("World")
    }
    println("Hello, ")
}

Hello
// (1 sec)
World
```

`coroutineScope`는 부모로부터 context를 상속받을 수 있고, `structured concurrency`를 지원한다.

## CoroutineScope의 종류

`coroutineScope`와 비슷하게 동작하는 함수들은 여러가지가 있다.

- **`supervisorScope`:** `coroutineScope`와 비슷하지만, `Job` 대신 `SupervisorJob`을 사용했다는 차이가 있다.
- **`withContext`:** coroutineContext를 변경할 수 있는 `coroutineScope`이다.
- **`withTimeout`:** timeout을 포함하고  있는 `coroutineScope`이다.

> 지금은 대략적으로만 설명하고, 뒤 챕터에서 더 자세히 설명한다.

지금 이렇게 설명한 이유는, 비슷한 함수들의 여러개가 있을 때 이름이 있어야 이해가 잘 되기 때문이다.

그렇다면 이들을 묶어서는 뭐라고 불러야 할까?

`scoping functions`이라고 부르는 사람들도 있는데, `scoping`이 정확히 뭘 의미하는지 알기 힘들기 때문에 살짝 헷갈리는 감이 없잖아 있다.

`scope functions`라고 부르기엔 kotlin의 `let`, `with`, `apply`와 헷갈릴 수 있다.

<br>

그렇다면 *coroutine scope functions*라는 이름은 어떤가?

더 길지만, 오해의 소지가 적으며, 명확하다.

<br>

또한, coroutine scope functions는 coroutine builder들과 햇갈리곤 한다.

하지만 개념적으로도 실질적으로도 틀렸다.

더 명확하게 표현하기 위해 다음 표를 보자.

| Coroutine Builders(runBlocking 제외)               | Coroutine Scope Functions                                    |
| -------------------------------------------------- | ------------------------------------------------------------ |
| `launch`, `async`, `produce`                       | `coroutineScope`, `supervisorScope`, `withContext`, `withTimeout` |
| `CoroutineScope`의 확장함수                        | suspend 함수                                                 |
| `CoroutineScope`에서 coroutine context를 획득한다. | suspend 함수의 continuation에서 coroutine context를 획득한다. |
| 부모 `Job`에게 예외가 전파된다.                    | 일반 함수처럼 예외가 던져진다.                               |
| 비동기로 coroutine을 실행한다.                     | 자신을 호출한 coroutine을 suspend 시킨다.                    |

이제 `runBlocking`에 대해 생각해 봐야 하는데, Coroutine Builder보다 Coroutine Scope Functions와 공통점이 더 많다.

`runBlocking`과 Coroutine Scope Functions와의 가장 큰 차이는 **`runBlocking`은 Blocking, Coroutine Scope는 suspend 함수 라는 것이다.**

이러한 이유 때문에 `runBlocking`이 최상위에서 사용되어야 하는 것이다.

### withContext

`withContext`는 `coroutineScope`와 비슷한데, 추가적으로 scope를 변경할 수 있다.

파라미터로 context를 넘겨서 부모의 scope를 변경할 수 있다.

즉, `withContext(EmptyCoroutineContext)`와 `coroutineScope()`는 완전히 동일하게 동작한다.

``` kotlin
fun CoroutineScope.log(text: String) {
    val name = this.coroutineContext[CoroutineName]?.name
    println("[$name] $text")
}

fun main() = runBlocking(CoroutineName("Parent")) {
    log("Before")
    withContext(CoroutineName("Child 1")) {
        delay(1000)
        log("Hello 1")
    }
    withContext(CoroutineName("Child 2")) {
        delay(1000)
        log("Hello 2")
    }
    log("After")
}

[Parent] Before
// (1 sec)
[Child 1] Hello 1
// 1초 뒤
[Child 2] Hello 2
[Parent] After
```

`withContext`는 일부분만 coroutine scope를 사용하고 싶을 때 사용하는데, 대부분 Dispatcher와 함께 사용한다.

``` kotlin
launch(Dispatchers.Main) {
    view.showProgressBar()
    withContext(Dispatchers.IO) {
        fileRepository.saveData(data)
    }
    view.hideProgressBar()
}
```

> `coroutineScope {}`는 `async {}.await()`와 거의 동일하게 동작한다.
>
> 또한 `async(context) {}.await()`과 `withContext(context) {}`도 거의 동일하다.
>
> 가장 큰 차이점은 **`async`는 scope를 필요로 하고, `withContext`나 `coroutineScope`는 suspend 함수에서 제공받는다.**
>
> 웬만하면 `async`에 바로 `await()`을 호출하는 것 보단 `withContext`나 `coroutineScope`를 지향하는 편이다.

### supervisorScope

`supervisorScope`도 `coroutineScope`와 거의 동일하게 동작한다.

부모의 scope를 받아 `coroutineScope`를 만들어 suspend block을 실행시킨다.

차이는 **Coroutine Context의 `Job`을 `SupervisorJob`으로 오버라이드 한다.**

``` kotlin
fun main() = runBlocking {
    println("Before")
    supervisorScope {
        launch {
            delay(1000)
            throw Error()
        }
        
        launch {
            delay(2000)
            println("Done")
        }
    }
    println("After")
}

Before
// 1초 뒤
Exception...
// 1초 뒤
Done
After
```

`supervisorScope`는 주로 여러 개별적인 작업들을 실행하고 싶을 때 사용한다.

``` kotlin
suspend fun notifyAnalytics(actions: List<UserAction>) = supervisorScope {
    actions.forEach { action ->
		launch {
            notifyAnalytics(action)
        }
	}
}
```

그렇다면 `withContext(SupervisorJob())`을 `supervisorScope` 대신 사용 할 수 있지 않을까?

언뜻보기엔 될 것 같지만, `withContext(SupervisorJob())`을 하면 **`SupervisorJob`의 자식으로 `Job`이 생기게 된다.**

따라서 우리가 생각하는 것과는 달리 예외가 부모로 전파되게 된다.

``` kotlin
fun main() = runBlocking {
    println("Before")
    withContext(SupervisorJob()) {
        launch {
            delay(1000)
            throw Error()
        }
        
        launch {
            delay(2000)
            println("Done")
        }
    }
    println("After")
}

Before
// (1 sec)
Exception...
```

### withTimeout

`withTimeout`도 `coroutineScope`와 거의 동일하게 동작하는데, 단지 body를 실행할 때 timeout이 추가될 뿐이다.

만약 timeout 안에 작업을 수행하지 못했다면 `TimeoutCancellationException`이 발생하게 된다

> `TimeoutCancellationException`은 `CancellationException`의 하위타입이다.

``` kotlin
suspend fun test(): Int = withTimeout(1500) {
    delay(1000)
    println("Still thinking")
    delay(1000)
    println("Done!")
    42
}
suspend fun main(): Unit = coroutineScope {
    try {
        test()
    } catch (e: TimeoutCancellationException) {
        println("Cancelled")
    }
    delay(1000)
}
// 1초 뒤
Still thinking
// 0.5초 뒤
Cancelled
```

`withTimeout`은 테스트를 할 때 유용하다.

어떤 함수가 몇 초 넘게, 혹은 몇 초 아래로 실행되었는지 테스트 할 수 있다.

> `@Test`에서 timeout을 설정한 것과 같다.

만약 `runBlockingTest` 안에서 사용되었다면 virtual time으로 실행시켜준다.

``` kotlin
class Test {
    @Test
    fun testTime2() = runTest {
        withTimeout(1000) {
            // 1000ms 아래로 소모되는 작업
            delay(900) // 가상 시간
        }
    }
    
	@Test(expected = TimeoutCancellationException::class)
    fun testTime1() = runTest {
        withTimeout(1000) {
            // 1000ms 위로 소모되는 작업
            delay(1100) // 가상 시간
        }
    }
    
    @Test
    fun testTime3() = runBlocking {
        withTimeout(1000) {
            delay(900)
        }
    }
}
```

주의할 점은 `withContext`는 `CancellationException`의 하위 타입인 `TimeoutCancellationException`을 던진다는 것이다.

즉, 예외가 발생해도 부모로 전파되지 않고 자신만 cancel된다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    launch { // withTimeout에서 발생한 예외로 인해 cancel된다.
        launch { // 부모가 cancel되었기 때문에 cancele된다.
            delay(2000)
            println("Will not be printed")
        }
        withTimeout(1000) { // CancellationException이 발생한다.
            delay(1500)
        }
    }
    
    launch { // CancellationException에 영향을 받지 않는다.
        delay(2000)
        println("Done")
    }
}

// 2초 뒤
// Done
```

<br>

`withTimeout`에서 예외를 던지는 대신 null을 반환해 주는 `withTimeoutOrNull`도 있다.

``` kotlin
suspend fun fetchUser(): User { // 무한으로 실행되는 메소드
    while (true) {
        yield()
    }
}

suspend fun getUserOrNull(): User? = withTimeoutOrNull(1000) {
    fetchUser()
}

suspend fun main(): Unit = coroutineScope {
    val user = getUserOrNull()
    println("User: $user")
}

// 1초 뒤
// User: null
```

### Coroutine Scope들의 기능 연결하기

두 Coroutine Scope들의 기능을 사용하고 싶을 땐 하나의 Coroutine Scope 안에 다른 CoroutineScope를 넣어주면 된다.

예를 들어, timeout과 Dispatcher를 설정해 주고 싶을 땐 다음과 같이 하면 된다.

``` kotlin
suspend fun getUserOrNull(): User? = withContext(Dispatchers.IO) {
    withTimeoutOrNull(1000) {
        fetchUserBlocking()
    }
}
```

## 추가적인 연산

어떤 처리를 하는 도중에 추가적인 연산을 실행시켜야 하면 어떻게 할까?

예를 들어, 프로필을 보여준 후에 분석을 위한 요청을 추가로 보내야 한다면 어떻게 할까?

많이들 `launch`를 같은 scope에서 실행하곤 한다.

``` kotlin
class ShowUserDataUseCase(
    private val repo: UserDataRepository,
    private val view: UserDataView,
) {
    suspend fun showUserData() = coroutineScope {
        // user profile을 조회해서 보여준다.
        val name = async { repo.getName() }
        
        val friends = async { repo.getFriends() }
        val profile = async { repo.getProfile() }
        val user = User(
            name = name.await(),
            friends = friends.await(),
            profile = profile.await()
        )
        
        view.show(user)
        
        // 추가적으로 프로필이 조회되었다는걸 알린다.
        launch { repo.notifyProfileShown() }
    }
}
```

하지만 이 방법은 다음과 같은 문제가 있다.

- `coroutineScope`는 모든 자식이 성공해야 하기 때문에 `launch`가 의미가 없다.
- 만약 `notifyProfileShown()`이 실패했다면 cancellation으로 인해 모든 process가 취소된다.

<br>

그렇다면 우리가 추가적이고, 크게 중요하지 않아 main process에 영향을 주면 안되는 작업을 해야 할 때 어떻게 해야할까?

이럴 때에는 다음과 같이 새로운 scope를 만들어야 한다.

``` kotlin
val analyticsScope = CoroutineScope(SupervisorJob())
```

scope를 제어하고 단위 테스트를 하기 위해서는 생성자로 주입하는게 낫다.

``` kotlin
class ShowUserDataUseCase(
    private val repo: UserDataRepository,
    private val view: UserDataView,
    private val analyticsScope: CoroutineScope,
) {
    suspend fun showUserData() = coroutineScope {
        val name = async { repo.getName() }
        val friends = async { repo.getFriends() }
        val profile = async { repo.getProfile() }
        val user = User(
            name = name.await(),
            friends = friends.await(),
            profile = profile.await()
        )
        view.show(user)
        analyticsScope.launch { repo.notifyProfileShown() }
    }
}
```

scope를 주입받아 연산을 수행하는건 일반적이다.

또한 usecase를 호출하는 쪽에서 개별적으로 실행될 수 있는지 알기 편하다.

