# WebClient Exception Handling

Mono는 Error 신호가 왔을 때 `.block()` 하려고 하면 **바로 예외를 던져준다.**

따라서 예외처리를 하기 전에 예외시의 처리를 따로 해주거나, 예외를 잡아줘야 한다.

<br>

- **예외를 잡는 방법**

`Assertions.assertThrows()` 메소드를 통해 예외 발생을 확인할 수 있다.

WebClient의 예외들은 `WebClientResponseException.class`를 상속한다.

따라서 WebClientResponseException이 throw 되었는지 확인하면 된다.

``` java
@Test
void deleteBeerByIdNotFound() {
    Assertions.assertThrows(WebClientResponseException.class, () ->
                            beerClient.deleteBeer(UUID.randomUUID()).block());
}
```

<br>

- **예외발생 시 처리하는 방법**

다른 방법으로는 **예외가 발생했을 때 ResponseEntity의 `status()`만 바꿔서 반환**하는 방법이 있다.

즉 오류 신호가 오게 되면 실제 Mono에서 신호를 받지 않고 무작정 ResponseEntity를 반환해 준다.

``` java
@Test
void deleteBeerByIdNotFound2() {
    Mono<ResponseEntity<Void>> responseEntityMono = beerClient.deleteBeer(UUID.randomUUID());

    ResponseEntity<Void> responseEntity = responseEntityMono.onErrorResume(throwable -> {
        if(throwable instanceof WebClientResponseException) {
            WebClientResponseException exception = (WebClientResponseException) throwable;
            return Mono.just(ResponseEntity.status(exception.getStatusCode()).build());
        } else {
            throw new RuntimeException(throwable);
        }
    }).block();

    Assertions.assertEquals(responseEntity.getStatusCode(), HttpStatus.NOT_FOUND);
}
```

위 코드는 조금 더 길어졌는데, 천천히 살펴보자

Mono의 `onErrorResume()`이라는 메소드는 Consumer에게 throwable을 전해줘서 처리하도록 해준다.

`onErrorResume()`는 **예외가 발생했을 때 실행**되는 메소드 인데, throwable이 만약 WebClientResponseException을 상속했다면

**ResponseEntity의 status가 throwable의 status인 ResponseEntity를 새로 만들어서 반환**해 준다.

즉 **흐름을 유지하되, ResponseEntity가 바뀌기 때문에 `.block()`의 입장에선 변조된 ResponseEntity의 신호만 받는다.** 

<br>

만약 WebClientResponseException을 상속한 예외가 아니라면 예기치 못한 예외이기 때문에 RuntimeException을 throw해 준다.